name: Test

on:
  workflow_dispatch:
    inputs:
      previous-run-id:
        description: "Previous run id to have the testing task retry failed tests"
        required: false
        type: string
      workflow-retry-count:
        type: choice
        description: "Counter for workflow retry attempts"
        default: '0'
        options:
          - '0'
          - '1'
          - '2'
          - '3'
          - '4'
          - '5'

  repository_dispatch:
    types: [test-main]
    inputs:
      previous-run-id:
        description: "Previous run id to have the testing task retry failed tests"
        type: string
        required: true
      workflow-retry-count:
        description: "Counter for workflow retry attempts"
        type: string
        required: true


env:
  BRANCH: ${{ github.event.ref || 'main'  }} # default branch for other trigger than 'workflow_dispatch'
  PREVIOUS_RUN_ID: ${{ inputs.previous-run-id || 'false' }} # default previous run id for other trigger than 'workflow_dispatch'
  RETRY_COUNT: ${{ inputs.workflow-retry-count || '0' }} # default retry count for other trigger than 'workflow_dispatch'
  RETRY_LIMIT: 5


jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 'Log env variables'
        run: |
          echo "env.BRANCH: ${{ env.BRANCH }}"
          echo "env.PREVIOUS_RUN_ID: ${{ env.PREVIOUS_RUN_ID }}"
          echo "env.RETRY_COUNT: ${{ env.RETRY_COUNT }}"

      - name: 'Read event inputs'
        if: ${{ github.event.action == 'test-main'}}
        run: |
          echo "${{ toJson(github.event) }}"
          echo "BRANCH=${{ github.event.branch }}" >> $GITHUB_ENV
          echo "PREVIOUS_RUN_ID=${{ github.event.client_payload.previous-run-id }}" >> $GITHUB_ENV
          echo "RETRY_COUNT=${{ github.event.client_payload.workflow-retry-count }}" >> $GITHUB_ENV
          echo "ACTION: ${{ github.event.action }}"

      - name: 'Log computetd env variables'
        run: |
          echo "env.BRANCH: ${{ env.BRANCH }}"
          echo "env.PREVIOUS_RUN_ID: ${{ env.PREVIOUS_RUN_ID }}"
          echo "env.RETRY_COUNT: ${{ env.RETRY_COUNT }}"

      - name: 'test-failure'
        run: |
          echo "Run in failure..."
          # Simulating a test failure for demonstration purposes
          exit 1

  check-test-results:
    if: ${{ always() && contains(needs.run-tests.result,'failure') }}
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: 'Retry Check'
        id: check
        run: |
          echo "env.PREVIOUS_RUN_ID: ${{ env.PREVIOUS_RUN_ID }}"
          echo "env.RETRY_COUNT: ${{ env.RETRY_COUNT }}"
          if [ ${{ env.RETRY_COUNT }} -lt ${{ env.RETRY_LIMIT }} ]; then
            echo "NEW_RETRY_COUNT=$(( ${{ env.RETRY_COUNT }} + 1 ))"
            echo "Retry limit (${{ env.RETRY_LIMIT }}) not reached. Triggering the $NEW_RETRY_COUNT. rerun."
            echo "Set new values..."
            echo "PREVIOUS_RUN_ID=${{ github.run_id }}" >> $GITHUB_ENV
            echo "RETRY_COUNT=$NEW_RETRY_COUNT" >> $GITHUB_ENV
            echo "PREVIOUS_RUN_ID to $PREVIOUS_RUN_ID"
            echo "RETRY_COUNT to $RETRY_COUNT"
          echo "TRIGGER_RETRY=true" >> $GITHUB_ENV
          else
            echo "Retry limit reached. Not retrying the workflow."
            echo "TRIGGER_RETRY=false" >> $GITHUB_ENV
          fi

      - name: Checkout
        if: ${{ env.TRIGGER_RETRY == 'true' }}
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/workflows/elion-e2e-test-rerun.yml

  logging:
    needs: [check-test-results, run-tests]
    if: ${{ always() && env.TRIGGER_RETRY == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: 'Logging retry properties'
        run: |
          echo "Trigger a new rerun..."
          echo "env.BRANCH: ${{ env.BRANCH }}"
          echo "env.RETRY_COUNT: ${{ env.PREVIOUS_RUN_ID }}"
          echo "env.PREVIOUS_RUN_ID: ${{ env.PREVIOUS_RUN_ID }}"


  rerun:
    needs: check-test-results
    if: ${{ always() && env.TRIGGER_RETRY == 'true' }}
    uses: './.github/workflows/test-main-rerun.yml'
    with:
      previous-run-id: ${{ env.PREVIOUS_RUN_ID }}
      workflow-retry-count: ${{ env.PREVIOUS_RUN_ID }}
    secrets: inherit