name: Test - Rerun

on:
  workflow_call:
    inputs:
      previous-run-id:
        description: "Previous run id to have the testing task retry failed tests"
        required: true
        type: string
      workflow-retry-count:
        description: "Counter for workflow retry attempts"
        type: string
        required: true

jobs:
  test-main:
    name: '${{ inputs.workflow-retry-count }}. Test - Rerun'
    runs-on: ubuntu-latest

    steps:
      - name: Logging inputs
        run: |
          echo "Previous run id: ${{ inputs.previous-run-id }}"
          echo "Workflow retry count: ${{ inputs.workflow-retry-count }}"

      - name: 'Dispatch rerun'
        uses: peter-evans/repository-dispatch@v4
        with:
          event-type: test-main
          client-payload: '{ "previous-run-id": "${{ inputs.previous-run-id }}", "workflow-retry-count":"${{ inputs.workflow-retry-count }}" }'
          token: '${{ secrets.REPOSITORY_DISPATCH_TOKEN }}'
