name: Test

on:
  workflow_dispatch:
    inputs:
      previous-run-id:
        description: "Previous run id to have the testing task retry failed tests"
        required: false
        type: string
      workflow-retry-count:
        type: choice
        description: "Counter for workflow retry attempts"
        default: '0'
        options:
          - '0'
          - '1'
          - '2'
          - '3'
          - '4'
          - '5'

  repository_dispatch:
    types: [test-main-1, test-main-2, test-main-3, test-main-4, test-main-5]
    inputs:
      previous-run-id:
        description: "Previous run id to have the testing task retry failed tests"
        type: string
        required: true
      workflow-retry-count:
        description: "Counter for workflow retry attempts"
        type: string
        required: true


env:
  BRANCH: ${{ github.event.ref || 'main'  }} # default branch for other trigger than 'workflow_dispatch'
  PREVIOUS_RUN_ID: ${{ inputs.previous-run-id || 'false' }} # default previous run id for other trigger than 'workflow_dispatch'
  RETRY_COUNT: ${{ inputs.workflow-retry-count || '0' }} # default retry count for other trigger than 'workflow_dispatch'
  RETRY_LIMIT: 5


jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 'Log inputs env variables'
        run: |
          echo "env.BRANCH: ${{ env.BRANCH }}"
          echo "env.PREVIOUS_RUN_ID: ${{ env.PREVIOUS_RUN_ID }}"
          echo "env.RETRY_COUNT: ${{ env.RETRY_COUNT }}"

      - name: 'Read event inputs'
        if: ${{ contains(github.event.action,'test-main') }}
        run: |
          echo "${{ toJson(github.event) }}"
          echo "BRANCH=${{ github.event.branch }}" >> $GITHUB_ENV
          echo "PREVIOUS_RUN_ID=${{ github.event.client_payload.previous-run-id }}" >> $GITHUB_ENV
          echo "RETRY_COUNT=${{ github.event.client_payload.workflow-retry-count }}" >> $GITHUB_ENV
          echo "ACTION: ${{ github.event.action }}"

      - name: 'Log computed env variables'
        run: |
          echo "env.BRANCH: ${{ env.BRANCH }}"
          echo "env.PREVIOUS_RUN_ID: ${{ env.PREVIOUS_RUN_ID }}"
          echo "env.RETRY_COUNT: ${{ env.RETRY_COUNT }}"

      - name: 'test-failure'
        run: |
          echo "Run in failure..."
          # Simulating a test failure for demonstration purposes
          exit 1

  check-tests:
    if: ${{ always() && contains(needs.run-tests.result,'failure') }}
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: 'Read "test-main" event inputs'
        if: ${{ contains(github.event.action,'test-main') }}
        run: |
          echo "${{ toJson(github.event) }}"
          echo "Event consumend: ${{ github.event.action }}"
          echo "BRANCH=${{ github.event.branch }}" >> $GITHUB_ENV
          echo "PREVIOUS_RUN_ID=${{ github.event.client_payload.previous-run-id }}" >> $GITHUB_ENV
          echo "RETRY_COUNT=${{ github.event.client_payload.workflow-retry-count }}" >> $GITHUB_ENV   

      - name: 'Check Retry'
        id: check
        run: |
          echo "BRANCH: ${{ env.BRANCH }}"
          echo "PREVIOUS_RUN_ID: ${{ env.PREVIOUS_RUN_ID }}"
          echo "RETRY_COUNT: ${{ env.RETRY_COUNT }}"
          echo "RETRY_LIMIT: ${{ env.RETRY_LIMIT }}"
          if [ ${{ env.RETRY_COUNT }} -lt ${{ env.RETRY_LIMIT }} ]; then
            NEW_RETRY_COUNT=$(( ${{ env.RETRY_COUNT }} + 1 ))
            NEW_PREVIOUS_RUN_ID=${{ github.run_id }}
            echo "Retry limit (${{ env.RETRY_LIMIT }}) not reached. Triggering the $NEW_RETRY_COUNT. rerun."
            echo "Set new values..."
            echo "PREVIOUS_RUN_ID to $NEW_PREVIOUS_RUN_ID"
            echo "RETRY_COUNT to $NEW_RETRY_COUNT"
            echo "previousRunId=$NEW_PREVIOUS_RUN_ID" >> $GITHUB_OUTPUT
            echo "retryCount=$NEW_RETRY_COUNT" >> $GITHUB_OUTPUT
            echo "triggerRetry=true" >> $GITHUB_OUTPUT
          else
            echo "Retry limit reached. Not retrying the workflow."
            echo "triggerRetry=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout
        if: ${{ steps.check.outputs.triggerRetry == 'true' }}
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/workflows/elion-e2e-test-rerun.yml

    outputs:
      triggerRetry: ${{ steps.check.outputs.triggerRetry }}
      previousRunId: ${{ steps.check.outputs.previousRunId }}
      retryCount: ${{ steps.check.outputs.retryCount }}

  logging:
    needs: [check-tests, run-tests]
    if: ${{ always() && needs.check-tests.outputs.triggerRetry == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: 'Logging retry properties'
        run: |
          echo "Trigger a new rerun with..."
          echo "branch: ${{ env.BRANCH }}"
          echo "retryCount: ${{ needs.check-tests.outputs.retryCount }}"
          echo "previousRunId: ${{ needs.check-tests.outputs.previousRunId }}"


  rerun:
    needs: check-tests
    if: ${{ always() && needs.check-tests.outputs.triggerRetry == 'true' }}
    uses: './.github/workflows/test-main-rerun.yml'
    with:
      previous-run-id: ${{ needs.check-tests.outputs.previousRunId }}
      workflow-retry-count: ${{ needs.check-tests.outputs.retryCount }}
    secrets: inherit